server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://localhost:5430/ddoormanDB
    username: usr
    password: pwd
  flyway:
    enabled: true
  kafka:
    partition: 1
    replicas: 1
    topic:
      name: requestEventTopic
    producer:
      bootstrap-servers: localhost:9092
      group-id: app
      auto-offset-reset: earliest
      key-serializer: org.apache.kafka.common.serialization.LongSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
  jackson:
    serialization:
      write-dates-as-timestamps: false

logging:
  level:
    org.springframework.jdbc.core.JdbcTemplate: TRACE